services:
  - type: web
    name: cockroach-poker
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
